### PR TITLE
Fixes issue #1 by adding the PPoRf prefix of the previous release ope…

### PR DESCRIPTION
**Pull request by JonasOberhauser**
…ration to the PPoRf prefix of the next release operation.

### CODE REVIEW

**Comment by michaliskok** [comment]
Hi Jonas,

Thanks for the issues and the pull request. 

I will pull this one internally for testing, and try to make a minor release that incorporates it (as well as a couple of other fixes for ppo) within this week.

Best,
Michalis

**Comment by JonasOberhauser** [comment]
Thanks Michalis,

Do you see any potential problems with the change? I was a bit uncomfortable at first but I think mathematically speaking it is sound

**Comment by michaliskok** [comment]
No, I do not see any problems; it actually captures the original intention of the code. 

The idea was that the pporf view of the event being added is going to be updated with the views of all the (read) events  of that thread. To optimize this a bit, we can only update with the events after the previous release operation and with the release itself, since the previous release will have already included the views of the reads before it. However, the update with the view of the previous release was missing from the code.

Thanks for catching that.

**Comment by michaliskok** [comment]
Pulled both this and #4 internally (part of v0.5.3).

**Pull request closed without merging**
